name: sales_forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - numpy=2.1.3
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - matplotlib=3.9.1
  - pip=25.0
  - setuptools=72.1.0
  - optuna=4.2.1
  - pip:
    - torchtriton==3.1.0
    - shap==0.46.0
